version: 1.0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm i @expo/webpack-config
        - npm install use-dynamic-refs --quiet expo-cli
        - npm install --quiet --global expo-cli
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: web-build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
