export const FETCH_ADMIN_ORDER_DETAIL_REQUEST =
  "FETCH_ADMIN_ORDER_DETAIL_REQUEST";
export const FETCH_ADMIN_ORDER_DETAIL_SUCCESS =
  "FETCH_ADMIN_ORDER_DETAIL_SUCCESS";
export const FETCH_ADMIN_ORDER_DETAIL_ERROR = "FETCH_ADMIN_ORDER_DETAIL_ERROR";
