export const FETCH_ADMIN_EMPLOYEE_BY_ORG_REQUEST =
  "FETCH_ADMIN_EMPLOYEE_BY_ORG_REQUEST";
export const FETCH_ADMIN_EMPLOYEE_BY_ORG_SUCCESS =
  "FETCH_ADMIN_EMPLOYEE_BY_ORG_SUCCESS";
export const FETCH_ADMIN_EMPLOYEE_BY_ORG_ERROR =
  "FETCH_ADMIN_EMPLOYEE_BY_ORG_ERROR";
