// Area //
export const FETCH_AREA_REQUEST = "FETCH_AREA_REQUEST";
export const FETCH_AREA_SUCCESS = "FETCH_AREA_SUCCESS";
export const FETCH_AREA_ERROR = "FETCH_AREA_ERROR";
export const ADD_AREA_REQUEST = "ADD_AREA_REQUEST";
export const ADD_AREA_SUCCESS = "ADD_AREA_SUCCESS";
export const ADD_AREA_ERROR = "ADD_AREA_ERROR";

// Area Pools //
export const FETCH_AREA_POOLS_SUCCESS = "FETCH_AREA_POOLS_SUCCESS";
export const FETCH_AREA_POOLS_ERROR = "FETCH_AREA_POOLS_ERROR";
