export const FETCH_AREA_REQUEST = "FETCH_AREA_REQUEST";
export const FETCH_AREA_SUCCESS = "FETCH_AREA_SUCCESS";
export const FETCH_AREA_ERROR = "FETCH_AREA_ERROR";
export const FETCH_AREA_POOLS_SUCCESS = "FETCH_AREA_POOLS_SUCCESS";
export const FETCH_AREA_POOLS_ERROR = "FETCH_AREA_POOLS_ERROR";
