export const FETCH_DAILY_CHECKLIST_REQUEST = "FETCH_DAILY_CHECKLIST_REQUEST";
export const FETCH_DAILY_CHECKLIST_SUCCESS = "FETCH_DAILY_CHECKLIST_SUCCESS";
export const FETCH_DAILY_CHECKLIST_ERROR = "FETCH_DAILY_CHECKLIST_ERROR";
