// get inventory //
export const FETCH_INVENTORY_ERROR = "FETCH_INVENTORY_ERROR";
export const FETCH_INVENTORY_REQUEST = "FETCH_INVENTORY_REQUEST";
export const FETCH_INVENTORY_SUCCESS = "FETCH_INVENTORY_SUCCESS";

// update invenoty item //
export const UPDATE_INVENTORY_ITEM_REQUEST = "UPDATE_INVENTORY_ITEM_REQUEST";
export const UPDATE_INVENTORY_ITEM_SUCCESS = "UPDATE_INVENTORY_ITEM_SUCCESS";
export const UPDATE_INVENTORY_ITEM_ERROR = "UPDATE_INVENTORY_ITEM_ERROR";

// add inventory item //
export const ADD_INVENTORY_ITEM_REQUEST = "ADD_INVENTORY_ITEM_REQUEST";
export const ADD_INVENTORY_ITEM_SUCCESS = "ADD_INVENTORY_ITEM_SUCCESS";
export const ADD_INVENTORY_ITEM_ERROR = "ADD_INVENTORY_ITEM_ERROR";
