export const FETCH_ORDER_DETAIL_REQUEST = "FETCH_ORDER_DETAIL_REQUEST";
export const FETCH_ORDER_DETAIL_SUCCESS = "FETCH_ORDER_DETAIL_SUCCESS";
export const FETCH_ORDER_DETAIL_ERROR = "FETCH_ORDER_DETAIL_ERROR";
export const FETCH_INDIVIDUAL_ORDER_DETAIL_ERROR = "FETCH_INDIVIDUAL_ORDER_DETAIL_ERROR";
export const FETCH_INDIVIDUAL_ORDER_DETAIL_SUCCESS = "FETCH_INDIVIDUAL_ORDER_DETAIL_SUCCESS";
