export const FETCH_ORDER_DETAIL_REQUEST = "FETCH_ORDER_DETAIL_REQUEST";
export const FETCH_ORDER_DETAIL_SUCCESS = "FETCH_ORDER_DETAIL_SUCCESS";
export const FETCH_ORDER_DETAIL_ERROR = "FETCH_ORDER_DETAIL_ERROR";
