export const FETCH_POOL_REQUEST = "FETCH_POOL_REQUEST";
export const FETCH_POOL_SUCCESS = "FETCH_POOL_SUCCESS";
export const FETCH_POOL_ERROR = "FETCH_POOL_ERROR";
export const FETCH_POOL_BY_ID_SUCCESS = "FETCH_POOL_BY_ID_SUCCESS";
export const FETCH_POOL_BY_ID_ERROR = "FETCH_POOL_BY_ID_ERROR";
