export const FETCH_POOL_REQUEST = "FETCH_POOL_REQUEST";
export const FETCH_POOL_SUCCESS = "FETCH_POOL_SUCCESS";
export const FETCH_POOL_ERROR = "FETCH_POOL_ERROR";
export const FETCH_POOL_BY_ID_SUCCESS = "FETCH_POOL_BY_ID_SUCCESS";
export const FETCH_POOL_BY_ID_ERROR = "FETCH_POOL_BY_ID_ERROR";

// ADD NEW POOL //
export const ADD_POOL_REQUEST = "ADD_POOL_REQUEST";
export const ADD_POOL_SUCCESS = " ADD_POOL_SUCCESS";
export const ADD_POOL_ERROR = "ADD_POOL_ERROR";
